development:
  clients:
    default:
      database: rails41_app_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: rails41_app_test
      hosts:
        - localhost:27017
